---

- name: python support
  when:
    - mariadb_python_packages is defined
    - mariadb_python_packages | length > 0
  block:
    - name: create pip requirements file
      bodsch.core.pip_requirements:
        name: mariadb
        requirements: "{{ mariadb_python_packages }}"
      register: pip_requirements

    - name: fail if pip not installed
      ansible.builtin.fail:
        msg: python pip is not installed
      when:
        - not pip_requirements.pip.present

    - name: install python packages  # noqa no-handler
      ansible.builtin.pip:
        state: present
        requirements: "{{ pip_requirements.requirements_file }}"
        extra_args: "{{ mariadb_python_extra_args | default([]) | bodsch.core.python_extra_args(python_version=ansible_python.version) | default(omit) }}"
      register: pip_install
      ignore_errors: true
      no_log: true
      when:
        - pip_requirements.requirements_file is defined
        - pip_requirements.changed

    - name: first run is failed, try with build
      when:
        - pip_install is defined
        - pip_install.failed is defined
        - pip_install.failed
        - mariadb_build_packages | default([]) | count > 0
      block:
        - name: install build essentials
          ansible.builtin.package:
            name: "{{ mariadb_build_packages }}"
            state: present

        - name: ensure python bindings for mariadb packages 2nd
          ansible.builtin.pip:
            state: present
            requirements: "{{ pip_requirements.requirements_file }}"
            extra_args: "{{ mariadb_python_extra_args | default([]) | bodsch.core.python_extra_args(python_version=ansible_python.version) | default(omit) }}"
          register: pip_install
          ignore_errors: false

        - name: uninstall build essentials
          ansible.builtin.package:
            name: "{{ mariadb_build_packages }}"
            state: absent

  rescue:
    - name: remove pip requirements
      bodsch.core.pip_requirements:
        name: mariadb
        requirements: "{{ mariadb_python_packages }}"
        state: absent

    - name: pip requirements installation failed
      ansible.builtin.fail:
        msg: "{{ pip_install.msg }}"
      when:
        - pip_install.failed

...
