---

- name: create neccessary directories
  file:
    path: '{{ mariadb_config_dir }}/conf.d'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: remove distribution directories
  file:
    path: "{{ mariadb_config_dir }}/mariadb.conf.d"
    state: absent

- name: create main configuration file
  template:
    src: "etc/my.cnf.j2"
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: 0644
    backup: true

- name: create configuration files
  template:
    src: "etc/mysql/conf.d/mysql.cnf.j2"
    dest: "{{ mariadb_config_include_dir }}/mysql.cnf"
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart mariadb

- name: create data directory '{{ mariadb_config_mysqld.datadir }}'
  file:
    path: "{{ mariadb_config_mysqld.datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  when:
    - mariadb_config_mysqld.datadir is defined
    - mariadb_config_mysqld.datadir != "/var/lib/mysql"

- name: create tmp directory '{{ mariadb_config_mysqld.tmpdir }}'
  file:
    path: "{{ mariadb_config_mysqld.tmpdir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  when:
    - mariadb_config_mysqld.tmpdir is defined
    - mariadb_config_mysqld.tmpdir != "/tmp"
    - mariadb_config_mysqld.tmpdir | length > 0

- name: create pid directory '{{ mariadb_config_mysqld["pid-file"] | dirname }}'
  file:
    path: "{{ mariadb_config_mysqld['pid-file'] | dirname }}"
    state: directory
    owner: mysql
    # group: mysql
    mode: 0755
  when:
    - mariadb_config_mysqld['pid-file'] is defined
    - mariadb_config_mysqld['pid-file'] | length > 0

# - block:
#     - name: create {{ systemd_lib_directory }}/{{ mariadb_service }}.service.d
#       file:
#         path: "{{ systemd_lib_directory }}/{{ mariadb_service }}.service.d"
#         state: directory
#         mode: 0750
#
#     - name: create overwrite.conf for systemd
#       template:
#         src: systemd/overwrite.conf.j2
#         dest: "{{ systemd_lib_directory }}/{{ mariadb_service }}.service.d/override.conf"
#         mode: 0440
#       notify:
#         - systemctl daemon-reload
#
#   when:
#     - ansible_service_mgr == "systemd"

- block:
    - name: create log directory '{{ mariadb_config_mysqld.slow_query_log_file }}'
      file:
        path: "{{ mariadb_config_mysqld.slow_query_log_file | dirname }}"
        state: directory
        owner: mysql
        group: adm
        mode: 0775

    - name: create slow query log file '{{ mariadb_config_mysqld.slow_query_log_file }}'
      file:
        path: "{{ mariadb_config_mysqld.slow_query_log_file }}"
        state: touch
        owner: mysql
        group: mysql
        mode: 0666
      changed_when: false

    - name: set ownership on slow query log file
      file:
        path: "{{ mariadb_config_mysqld.slow_query_log_file }}"
        state: file
        owner: mysql
        group: mysql
        mode: 0666
  when:
    - mariadb_config_mysqld.slow_query_log_file is defined
    - mariadb_config_mysqld.slow_query_log_file | length > 0
    # - mariadb_slow_query_log_enabled

- block:
    - name: create log directory '{{ mariadb_config_mysqld.log_error }}'
      file:
        path: "{{ mariadb_config_mysqld.log_error | dirname }}"
        state: directory
        owner: mysql
        group: adm
        mode: 0775

    - name: create error log file '{{ mariadb_config_mysqld.log_error }}'
      file:
        path: "{{ mariadb_config_mysqld.log_error }}"
        state: touch
        owner: mysql
        group: mysql
        mode: 0666
      changed_when: false

    - name: set ownership on error log file
      file:
        path: "{{ mariadb_config_mysqld.log_error }}"
        state: file
        owner: mysql
        group: mysql
        mode: 0666
  when:
    - mariadb_config_mysqld.log_error is defined
    - mariadb_config_mysqld.log_error | length > 0

- name: configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness | int }}"
    state: present
  when:
    - mariadb_configure_swappiness | bool

- name: run bootstrap on custom data directories '{{ mariadb_config_mysqld.datadir }}'
  mariadb_bootstrap:
    datadir: "{{ mariadb_config_mysqld.datadir }}"
    skip_test_db: false
  when:
    - mariadb_config_mysqld.datadir is defined
    - mariadb_config_mysqld.datadir != "/var/lib/mysql"

- name: start mariadb first time
  service:
    name: '{{ mariadb_service }}'
    state: started
  register: service_status
  notify:
    - wait 20 seconds for clean startup

# - name: service state
#   debug:
#     var: "{{ item }}"
#   when: item is defined
#   loop:
#     - service_status.state
#     - service_status.failed

...
