---

- name: create or remove mariadb databases
  when:
    - not mariadb_galera_cluster or (mariadb_galera_cluster and mariadb_galera_primary_node == ansible_hostname)
  run_once: "{{ 'true' if mariadb_galera_cluster else 'false' }}"
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
    login_user:  "{{ _mariadb_root_system_user.username }}"
    login_password: "{{ _mariadb_root_system_user.password }}"
    login_unix_socket: "{{ mariadb_socket | default(omit) }}"
    config_file: "{{ _mariadb_root_system_user.home | default('/root') }}/.my.cnf"
  loop:
    '{{ mariadb_databases }}'
  loop_control:
    label: " schema: {{ item.name }} with collation: {{ item.collation | default('utf8_general_ci') }}"

...
