---

- name: ensure mariadb packages are installed (debian)
  package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_install_packages
  when:
    ansible_os_family | lower == 'debian'

- block:
    - name: ensure mariadb packages are installed (centos < 8)
      package:
        name: "{{ mariadb_packages }}"
        state: present
        use: yum
      register: mariadb_install_packages
      when: ansible_distribution_version | int < 8

    - name: ensure mariadb packages are installed (centos >= 8)
      package:
        name: "{{ mariadb_packages }}"
        state: present
        use: dnf
      register: mariadb_install_packages
      when: ansible_distribution_version | int >= 8

  when: ansible_os_family | lower == 'redhat'

- name: ensure python bindings for mariadb are installed
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  loop:
    "{{ mariadb_python_packages }}"
  register: mariadb_install_python_packages
