---

- name: create policy-rc.d
  copy:
    dest: /usr/sbin/policy-rc.d
    content: |
      #!/bin/sh
      exit 101
    mode: 0755
  when:
    - not mariadb_installed
    - ansible_os_family | lower != 'archlinux'

- name: ensure mariadb packages are installed
  package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_install_packages

- name: fix debian specific debian-start file
  template:
    src: etc/mysql/debian-start.j2
    dest: "{{ mariadb_config_dir }}/debian-start"
    mode: 0755
  when:
    - ansible_os_family | lower == 'debian'

- name: remove policy-rc.d
  file:
    path: /usr/sbin/policy-rc.d
    state: absent
  when:
    - ansible_os_family | lower != 'archlinux'

- name: python support
  when:
    - mariadb_python_packages is defined
    - mariadb_python_packages | length > 0
  block:
    - name: create requirements.txt
      template:
        src: requirements.txt.j2
        dest: /tmp/mariadb-requirements.txt
        mode: 0660

    - name: ensure python bindings for mariadb packages 1st
      pip:
        requirements: /tmp/mariadb-requirements.txt
        state: present
        executable: pip{{ '3' if ansible_python.version.major | int == 3 else '' }}
      register: pip_install
      ignore_errors: true
      no_log: true

    - name: use build tools
      when:
        - pip_install.failed
      block:
        - name: install build essentials
          package:
            name: "{{ mariadb_build_packages }}"
            state: present

        - name: ensure python bindings for mariadb packages 2nd
          pip:
            requirements: /tmp/mariadb-requirements.txt
            state: present
            executable: pip{{ '3' if ansible_python.version.major | int == 3 else '' }}

        - name: uninstall build essentials
          package:
            name: "{{ mariadb_build_packages }}"
            state: absent

- name: install mysqltuner
  get_url:
    url: "https://raw.githubusercontent.com/major/MySQLTuner-perl/master/{{ item.name }}"
    dest: /usr/local/bin/{{ item.name }}
    mode: "{{ item.mode }}"
  register: _download_mysqltuner
  until: _download_mysqltuner is succeeded
  retries: 5
  delay: 2
  check_mode: false
  loop:
    - name: mysqltuner.pl
      mode: 0o750
    - name: basic_passwords.txt
      mode: 0o640
    - name: vulnerabilities.csv
      mode: 0o640
  loop_control:
    label: "{{ item.name }}"
  when:
    - mariadb_mysqltuner

...
