---

- include_tasks: prepare.yaml

- include_tasks: detect_mariadb_version.yml

- include_tasks: installation.yml

- name: configure mariadb
  include_tasks: configure.yml

- name: security changes
  include_tasks: secure-installation.yml

- name: create monitoring stuff
  include_tasks: monitoring.yml

- name: create databases
  include_tasks: databases.yml

- name: create users
  include_tasks: users.yml

- include_tasks: replication.yml
  when:
    - mariadb_replication.role is defined
    - mariadb_replication.role | length > 0
    - mariadb_replication.role in ['master', 'replica']

- name: ensure mariadb is enabled on boot
  service:
    name: '{{ mariadb_service }}'
    enabled: true

...
