---

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: 'setup-{{ansible_os_family | lower}}.yml'

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: monitoring.yml
- include_tasks: databases.yml
- include_tasks: users.yml
#- include_tasks: replication.yml
