---

- block:
    - name: create monitoring database
      mysql_db:
        name: monitoring
        collation: 'utf8_general_ci'
        encoding: 'utf8'
        state: present

    - name: create monitoring user
      mysql_user:
        name: "{{ mariadb_monitoring.username }}"
        host: '%'
        password: "{{ mariadb_monitoring.password }}"
        priv: 'monitoring.*:ALL'
        state: present
        append_privs: false
        encrypted: false
        update_password: on_create
      no_log: true

    - name: create my.cnf file with password credentials
      template:
        src: monitoring-my.cnf.j2
        dest: /usr/local/etc/.my.cnf
        owner: '{{ mariadb_monitoring.system_user }}'
        mode: 0644
        backup: true
  when:
    - mariadb_monitoring is defined
    - mariadb_monitoring.enabled | bool
    - mariadb_monitoring.system_user is defined
    - mariadb_monitoring.system_user | length != 0
    - mariadb_monitoring.username is defined
    - mariadb_monitoring.username | length != 0

...
