---

- block:
    - name: create monitoring database
      mysql_db:
        name: monitoring
        collation: 'utf8_general_ci'
        encoding: 'utf8'
        state: present

    - name: create monitoring user
      mysql_user:
        name: monitoring
        host: '%'
        password: monitoring
        priv: 'monitoring.*:ALL'
        state: present
        append_privs: false
        encrypted: false
        update_password: on_create
      no_log: true

    - name: create my.cnf file with password credentials
      template:
        src: monitoring-my.cnf.j2
        dest: /usr/local/etc/.my.cnf
        owner: '{{ mariadb_monitoring_user }}'
        mode: 0644
  when:
    - mariadb_monitoring is defined
    - mariadb_monitoring | bool
    - mariadb_monitoring_user is defined
    - mariadb_monitoring_user | length != 0

...
