---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- block:
    - name: make sure python3-apt is installed (only debian based)
      package:
        name:
          - python3-apt
        state: present

    - name: clean apt cache
      command: apt-get clean
      args:
        warn: false
  when:
    - ansible_os_family | lower == 'debian'

- name: merge mariadb configuration segment for server between defaults and custom
  set_fact:
    mariadb_config_server: "{{ mariadb_config_defaults_server |
      combine( mariadb_config_server, recursive=True ) }}"

- name: merge mariadb configuration segment for client between defaults and custom
  set_fact:
    mariadb_config_client: "{{ mariadb_config_defaults_client |
      combine( mariadb_config_client, recursive=True ) }}"

- name: merge mariadb configuration segment for mysql between defaults and custom
  set_fact:
    mariadb_config_mysql: "{{ mariadb_config_defaults_mysql |
      combine( mariadb_config_mysql, recursive=True ) }}"

- name: merge mariadb configuration segment for mysqld between defaults and custom
  set_fact:
    mariadb_config_mysqld: "{{ mariadb_config_defaults_mysqld |
      combine( mariadb_config_mysqld, recursive=True ) }}"

- name: merge mariadb configuration segment for mysqld_safe between defaults and custom
  set_fact:
    mariadb_config_mysqld_safe: "{{ mariadb_config_defaults_mysqld_safe |
      combine( mariadb_config_mysqld_safe, recursive=True ) }}"

- name: merge mariadb configuration segment for mysqldump between defaults and custom
  set_fact:
    mariadb_config_mysqldump: "{{ mariadb_config_defaults_mysqldump |
      combine( mariadb_config_mysqldump, recursive=True ) }}"

- name: merge mariadb configuration segment for galera between defaults and custom
  set_fact:
    mariadb_config_galera: "{{ mariadb_config_defaults_galera |
      combine( mariadb_config_galera, recursive=True ) }}"

- name: merge mariadb configuration segment for emmbedded between defaults and custom
  set_fact:
    mariadb_config_embedded: "{{ mariadb_config_defaults_embedded |
      combine( mariadb_config_embedded, recursive=True ) }}"

- name: merge mariadb custom configurations between defaults and custom
  set_fact:
    mariadb_config_custom: "{{ mariadb_config_defaults_custom |
      combine( mariadb_config_custom, recursive=True ) }}"

- name: merge mariadb replication between defaults and custom
  set_fact:
    mariadb_replication: "{{ mariadb_defaults_replication |
      combine( mariadb_replication, recursive=True ) }}"

- name: create mariadb repository
  template:
    src: etc/mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: 0750
  when:
    - mariadb_use_external_repo | bool
    - ansible_os_family | lower == 'redhat'

- block:
    - name: add apt signing key
      apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present

    - name: add mariadb repository for debian
      apt_repository:
        repo: "deb {{ mariadb_debian_repo }}/{{ mariadb_version }}/{{ ansible_os_family | lower }} {{ ansible_distribution_release | lower }} main"
        state: present
      when:
        - ansible_distribution | lower == 'debian'

    - name: add mariadb repository for ubuntu
      apt_repository:
        repo: "deb {{ mariadb_debian_repo }}/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"
        state: present
      when:
        - ansible_distribution | lower == 'ubuntu'

  when:
    - mariadb_use_external_repo | bool
    - ansible_os_family | lower == 'debian'

- name: update package cache
  package:
    update_cache: true

- name: detect if mariadb installed
  stat:
    path: /usr/bin/mysqld_safe
  register: mysqld_binary_file

- name: detect if mariadb installed
  set_fact:
    mariadb_installed: "{{ mysqld_binary_file.stat.exists }}"
  when:
    - mysqld_binary_file is defined
    - mysqld_binary_file.stat is defined

- name: do facts module to get latest information
  setup:

...
