---

- block:
    - name: ensure the ansible_python_interpreter is set to python2
      set_fact:
        ansible_python_interpreter: python2

    - name: do facts module to get latest information
      setup:
  when: (
    ansible_os_family | lower == 'redhat' and
    ansible_distribution_version | int < 8)

- block:
    - name: add mariadb repository
      yum_repository:
        name: MariaDB
        state: present
        description: MariaDB {{ mariadb_version }} CentOS repository {{ ansible_distribution_major_version }} - amd64
        baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos{{ ansible_distribution_major_version }}-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: 1
        enabled: 1

    - name: enable module_hotfixes
      ini_file:
        dest: /etc/yum.repos.d/MariaDB.repo
        section: MariaDB
        option: module_hotfixes
        value: "1"
        mode: 0750

    - name: update rpm cache
      yum:
        update_cache: true
  when: (
    mariadb_use_external_repo | bool and
    ansible_os_family | lower == 'redhat')

- block:
    - name: update apt cache
      apt:
        update_cache: true

    - name: install requierements
      package:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common
        - dirmngr

    - name: add apt signing key
      apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present

    - name: add mariadb repository for debian
      apt_repository:
        repo: "deb {{ mariadb_debian_repo }}/{{ mariadb_version }}/{{ ansible_os_family | lower }} {{ ansible_distribution_release | lower }} main"
        state: present
      when:
        ansible_distribution | lower == 'debian'

    - name: add mariadb repository for ubuntu
      apt_repository:
        repo: "deb {{ mariadb_debian_repo }}/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"
        state: present
      when:
        ansible_distribution | lower == 'ubuntu'

    - name: update apt cache
      apt:
        update_cache: true
  when: (
    mariadb_use_external_repo | bool and
    ansible_os_family | lower == 'debian')
