---
- name: Ensure replication user exists on master.
  mysql_user:
    name: "{{ mariadb_replication_user.name }}"
    host: "{{ mariadb_replication_user.host | default('%') }}"
    password: "{{ mariadb_replication_user.password }}"
    priv: "{{ mariadb_replication_user.priv | default('*.*:REPLICATION SLAVE,REPLICATION CLIENT') }}"
    state: present
  when: >
    (mariadb_replication_role == 'master')
    and mariadb_replication_user
    and (mariadb_replication_master != '')

- name: Check slave replication status.
  mysql_replication:
    mode: getslave
    login_user: "{{ mariadb_replication_user.name }}"
    login_password: "{{ mariadb_replication_user.password }}"
  ignore_errors: true
  register: slave
  when: >
    mariadb_replication_role == 'slave'
    and (mariadb_replication_master != '')

- name: Check master replication status.
  mysql_replication:
    mode: getmaster
  delegate_to: "{{ mariadb_replication_master }}"
  register: master
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')

- name: Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    master_host: "{{ mariadb_replication_master }}"
    master_user: "{{ mariadb_replication_user.name }}"
    master_password: "{{ mariadb_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: true
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')
    and mariadb_replication_user

- name: Start replication.
  mysql_replication:
    mode: startslave
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')
