---

- name: use external repository
  when:
    - mariadb_use_external_repo | bool
  block:
    - name: debian
      when:
        - ansible_os_family | lower == 'debian'
      block:
        - name: add apt signing key
          ansible.builtin.apt_key:
            url: https://mariadb.org/mariadb_release_signing_key.asc
            state: present
          register: apt_key
          changed_when: apt_key.changed
          failed_when: apt_key.failed

        - name: install mariadb repositories for debian based
          ansible.builtin.template:
            src: etc/apt/mariadb.list.j2
            dest: /etc/apt/sources.list.d/mariadb.list
            mode: "0644"
            owner: root
            group: root
          register: apt_repo
          changed_when: apt_repo.changed
          failed_when: apt_repo.failed

        - name: clean apt cache   # noqa command-instead-of-module
          ansible.builtin.command: |
            apt-get clean
          register: bash_output
          changed_when: bash_output.rc != 0
          failed_when: bash_output.rc != 0
          when:
            - "ansible_version.full is version_compare('2.13', '<')"
            - apt_key.changed
            - apt_repo.changed

        - name: clean apt cache
          ansible.builtin.apt:
            clean: true
          when:
            - "ansible_version.full is version_compare('2.13', '>=')"
            - apt_key.changed
            - apt_repo.changed

- name: remove external repository
  when:
    - not mariadb_use_external_repo | bool
  ansible.builtin.file:
    state: absent
    path: /etc/apt/sources.list.d/mariadb.list
  register: apt_ext_repo
  changed_when: apt_ext_repo.changed
  failed_when: apt_ext_repo.failed

- name: update package cache
  ansible.builtin.package:
    update_cache: true
  when:
    - apt_ext_repo.changed

...
