---

- name: use external repository
  when:
    - mariadb_use_external_repo | bool
  block:
    - name: create mariadb repository
      ansible.builtin.template:
        src: etc/yum/mariadb.repo.j2
        dest: /etc/yum.repos.d/MariaDB.repo
        mode: 0750
      when:
        - ansible_os_family | lower == 'redhat'

    - name: debian
      when:
        - ansible_os_family | lower == 'debian'
      block:
        - name: add apt signing key
          ansible.builtin.apt_key:
            url: https://mariadb.org/mariadb_release_signing_key.asc
            state: present

        - name: install mariadb repositories for debian based
          ansible.builtin.template:
            src: etc/apt/mariadb.list.j2
            dest: /etc/apt/sources.list.d/mariadb.list
            mode: 0644
            owner: root
            group: root

        - name: clean apt cache
          ansible.builtin.apt:
            clean: true

    - name: update package cache
      ansible.builtin.package:
        update_cache: true

...
