---

- name: validate custom root password
  when:
    - mariadb_root_password | length == 0
  block:
    - name: warn if a custom root password is not specified
      ansible.builtin.fail:
        msg: |
          - WARNING -
          The MariaDB root password was left empty.
          Please set a custom password with role variable 'mariadb_root_password'
          to secure your database server!
      ignore_errors: true

    - name: wait 10 seconds to realise the message
      delegate_to: localhost
      ansible.builtin.wait_for:
        timeout: 10

- name: set database root password
  mariadb_root_password:
    dba_root_username: "{{ mariadb_root_username }}"
    dba_root_password: "{{ mariadb_root_password }}"
    dba_bind_address: "{{ mariadb_bind_address | default(omit) }}"
    dba_socket: "{{ mariadb_socket | default(omit) }}"
    dba_config_directory: "{{ mariadb_config_dir }}"
    mycnf_file: "{{ mariadb_root_home }}/.my.cnf"

- name: secure database (remove anonymous user, disallow remote root login, ...)
  when:
    - not mariadb_galera_cluster or (mariadb_galera_cluster and mariadb_galera_primary_node == ansible_hostname)
  mariadb_secure:
    disallow_anonymous_users: true
    disallow_test_database: true
    disallow_remote_root_login: true

...
