---

- name: check if a custom root password is specified
  debug:
    msg: >
      Warning!!
      The MariaDB root password was left empty.
      Please set a custom password with role variable mariadb_root_password
      to secure your database server!
  when:
    - mariadb_root_password | length == 0

- name: set MariaDB root password
  mariadb_root_password:
    dba_root_username: "{{ mariadb_root_username }}"
    dba_root_password: "{{ mariadb_root_password }}"
    dba_socket: "{{ mariadb_socket }}"
    dba_config_directory: "{{ mariadb_config_dir }}"
    mycnf_file: "{{ mariadb_root_home }}/.my.cnf"

- name: secure MariaDB
  mariadb_secure:
    disallow_anonymous_users: true
    disallow_test_database: true
    disallow_remote_root_login: true

...
