---

- name: create or remove mariadb users
  when:
    - not mariadb_galera_cluster or (mariadb_galera_cluster and mariadb_galera_primary_node == ansible_hostname)
  run_once: "{{ 'true' if mariadb_galera_cluster else 'false' }}"
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('false') }}"
    encrypted: "{{ item.encrypted | default('true') }}"
    login_user:  "{{ _mariadb_root_system_user.username }}"
    login_password: "{{ _mariadb_root_system_user.password }}"
    login_unix_socket: "{{ mariadb_socket | default(omit) }}"
    config_file: "{{ _mariadb_root_system_user.home | default('/root') }}/.my.cnf"
  loop:
    '{{ mariadb_users }}'
  loop_control:
    label: "{{ item.name }}, state: {{ item.state | default('present') }}"
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"

...
