---

- name: create or remove mariadb users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('false') }}"
    encrypted: "{{ item.encrypted | default('true') }}"
  loop:
    '{{ mariadb_users }}'
  loop_control:
    label: "{{ item.name }}, state: {{ item.state | default('present') }}"
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"

...
