---

mariadb_use_external_repo: true
mariadb_version: 10.4

mariadb_root_password: "" # Y5FZfKXzCeOWGf4kBOiFSp6Il

mariadb_databases:
  - name: molecule
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:
  - name: molecule
    host: '%'
    password: molecule
    priv: "molecule.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind_address: 127.0.0.1
  socket: "{{ mariadb_socket }}"
  skip_external_locking:
  skip_name_resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20
