---

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart mariadb
  ansible.builtin.service:
    name: '{{ mariadb_service }}'
    state: restarted
  notify:
    - wait 2 seconds for clean startup

- name: wait 2 seconds for clean startup
  ansible.builtin.pause:
    seconds: 2
