---

- name: systemctl daemon-reload
  systemd:
    daemon_reload: true

- name: restart mariadb
  service:
    name: '{{ mariadb_service }}'
    state: restarted
  notify:
    - wait 2 seconds for clean startup

- name: wait 2 seconds for clean startup
  pause:
    seconds: 2
