---
- hosts: all
  any_errors_fatal: false
  gather_facts: true
  environment:
    NETRC: ''
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:
    - role: ansible-mariadb
      vars:
        # ansible_python_interpreter: python3
        mariadb_root_password: root_password
