---

# ansible_python_interpreter: python3

mariadb_use_external_repo: false

mariadb_bind_address: 127.0.0.1
mariadb_root_password: root_password
mariadb_max_connections: 20

mariadb_databases:
  - name: molecule
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:
  - name: molecule
    host: '%'
    password: molecule
    priv: "molecule.*:ALL"

mariadb_config_mysqld:
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  # Skip reverse DNS lookup of clients
  skip-name-resolve: 1
  # enable performance schema
  performance_schema: 1
  datadir: /opt/mariadb/data
  tmpdir: /opt/mariadb/tmp
  log_error: /opt/mariadb/log/error.log
  slow_query_log_file: /opt/mariadb/log/mysql-slow.log
  expire_logs_days: 2
