---

- name: "detect bootstraped database"
  ansible.builtin.stat:
    path: "{{ mariadb_galera_states.wsrep_bootstrapped }}"
  register: _bootstraped_database

- name: define facts
  ansible.builtin.set_fact:
    galera_bootstraped_database: "{{ _bootstraped_database.stat.exists | default('false') }}"

- name: create wsrep_notify script
  ansible.builtin.template:
    src: "bin/wsrep_notify.sh.j2"
    dest: "/bin/wsrep_notify.sh"
    owner: root
    group: mysql
    mode: "0770"

- name: galera cluster mode
  when:
    - mariadb_galera_cluster
    - not galera_bootstraped_database
  block:

    - name: setup primary instance
      ansible.builtin.include_tasks: galera/primary.yml
      when:
        - mariadb_galera_primary_node == ansible_hostname
        - not galera_bootstraped_database

    - name: setup secondary instances
      ansible.builtin.include_tasks: galera/secondary.yml
      when:
        - not mariadb_galera_primary_node == ansible_hostname

    - name: reconfigure primary instance
      ansible.builtin.include_tasks: galera/primary_reconfigure.yml
      when:
        - mariadb_galera_primary_node == ansible_hostname

  rescue:

    - name: stop mariadb service bootstrap mode
      ansible.builtin.service:
        name: "{{ mariadb_service }}"
        state: stopped

    - name: remove wsrep.cnf
      ansible.builtin.file:
        state: absent
        path: "{{ mariadb_config_include_dir }}/99-wsrep.cnf"

    # - name: remove bootstraped tag
    #   ansible.builtin.file:
    #     state: absent
    #     path: "{{ mariadb_galera_states.wsrep_bootstrapped }}"

    # - name: remove {{ mariadb_config_mysqld.datadir }}/gvwstate.dat
    #   ansible.builtin.file:
    #     state: absent
    #     path: "{{ mariadb_config_mysqld.datadir }}/gvwstate.dat"
    #
    # - name: remove {{ mariadb_config_mysqld.datadir }}/grastate.dat
    #   ansible.builtin.file:
    #     state: absent
    #     path: "{{ mariadb_config_mysqld.datadir }}/grastate.dat"

    - name: exit with fail
      ansible.builtin.fail:
        msg: "Error while creating the initial database structure!"

- name: cluster information
  block:
    - name: get galera cluster state
      community.mysql.mysql_query:
        query: SHOW status WHERE Variable_Name IN ('wsrep_ready', 'wsrep_cluster_status', 'wsrep_connected','wsrep_cluster_size')
        login_unix_socket: "{{ mariadb_socket | default(omit) }}"
      register: _wsrep_state

    - name: galera cluster state
      ansible.builtin.debug:
        msg: "{{ _wsrep_state.query_result }}"

...
