---

mariadb_system_users:
  - username: root
    password: Y5FZfKXzCeOWGf4kBOiFSp6Il
    home: /root
    update: true
    ignore: false

mariadb_databases:
  - name: molecule
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:
  - name: molecule
    host: '%'
    password: molecule
    priv: "molecule.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind-address: 127.0.0.1
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20

  datadir: /opt/mariadb/data
  tmpdir: /opt/mariadb/tmp
  log_error: /opt/mariadb/log/error.log
  slow_query_log_file: /opt/mariadb/log/mysql-slow.log
