---

mariadb:
  galera:
    cluster_name: molecule-cluster
    node_addresses: "{{ groups['mariadb'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
    sst:
      method: "rsync"
      auth:
        username: "cluster-admin"
        password: "c1ust3R"
    node:
      name: "{{ ansible_hostname }}"
      id: "{{ mariadb_server_id }}"
      address: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"
    gtid_domain_id: "{{ mariadb_server_id }}"

  proxy_protocol_networks:
    - "127.0.0.1/32"
    - "10.29.0.0/24"
